# Generated by Django 6.0 on 2026-01-12 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="rollno",
            field=models.IntegerField(default=0),
        ),
    ]
